"""Builds tracker/exercise-images.js: exercise name -> photo file stem in workouts/img.
Run from the repo root after adding or renaming exercises on the workout pages:
    python3 tools/build-exercise-images.py
"""
import glob, html, json, re

norm = lambda s: re.sub(r"[^a-z0-9]+", " ", s.lower()).strip()
images = {}
for page in sorted(glob.glob("workouts/**/index.html", recursive=True)):
    text = open(page, encoding="utf-8").read()
    for name, body in re.findall(r"<li><h3>(.*?)</h3>(.*?)</li>", text, re.S):
        name = html.unescape(re.sub(r"<[^>]+>", "", name))
        img = re.search(r'src="(?:\.\./)+img/([^"]+?)-0\.jpg"', body)
        if img:
            images.setdefault(norm(name), img.group(1))

# Template exercises that aren't on a workout page but have a close match.
EXTRA = {
    "Sit-to-Stand (chair squat)": "bodyweight-squat",
    "Suitcase Carry": "farmers-walk",
    "Single-Leg Calf Raise": "standing-calf-raises",
}
for name, stem in EXTRA.items():
    images.setdefault(norm(name), stem)

with open("tracker/exercise-images.js", "w", encoding="utf-8") as f:
    f.write("// Generated by tools/build-exercise-images.py. Exercise name -> photo in workouts/img.\n")
    f.write("window.EXERCISE_IMAGES = " + json.dumps(dict(sorted(images.items())), indent=0) + ";\n")
print(len(images), "exercises with photos")
